import turtle as t
import math
t.speed(100)
t.screensize(800,600)

def baowei(x,y,height,lenth):
    t.seth(0)
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.right(90)
    t.fd(height)
    t.right(90)
    t.fd(lenth)
    t.right(90)
    t.fd(height)

def shenti():
    t.penup()
    t.goto(-180, 300 + 5 * math.sin(-18))
    t.pendown()

    #身体主部分
    t.color("black","yellow")
    t.begin_fill()
    tx = -180
    ty = 300
    while tx < 180:
        t.goto(tx, ty + 5 * math.sin(tx / 10))
        tx += 1
    while ty > 19:
        t.goto(tx + 5 * math.sin(ty / 10) + 3, ty)
        ty -= 1
    t.end_fill()

    t.color("black","yellow")
    t.begin_fill()
    tx = -180
    while ty < 310:
        t.goto(tx + 5 * math.sin(ty / 10) + 3, ty)
        ty += 1
    t.penup()
    t.goto(180 + 5 * math.sin(20 / 10) + 3, 20)
    t.end_fill()

def kuzi():
    tx=180
    ty=20
    t.color("black", "white")
    t.begin_fill()
    t.penup()
    t.goto(tx + 5 * math.sin(ty / 10) + 3, ty)
    t.pendown()
    baowei(tx + 5 * math.sin(ty / 10) + 3, ty, 50, 360)
    t.end_fill()
    #领带
    t.penup()
    t.goto(-80,20)
    t.pendown()
    t.seth(-30)
    t.fd(50)
    t.left(80)
    t.fd(32)

    t.penup()
    t.goto(80, 20)
    t.pendown()
    t.seth(-150)
    t.fd(50)
    t.right(80)
    t.fd(32)

    t.color("black", (0.5,0.2,0.1))
    t.penup()
    t.goto(tx + 5 * math.sin(ty / 10) + 3, ty-50)
    t.pendown()
    t.begin_fill()
    baowei(tx + 5 * math.sin(ty / 10) + 3, ty-50, 50, 360)
    t.end_fill()

    #红领带
    t.penup()
    t.goto(25, 10)
    t.pendown()
    t.color("black","red")
    t.begin_fill()
    t.seth(130)
    t.fd(10)
    t.left(50)
    t.fd(35)
    t.left(50)
    t.fd(10)
    t.left(70)
    t.fd(15)
    t.left(60)
    t.fd(35)
    t.left(60)
    t.fd(15)
    t.end_fill()

    t.penup()
    t.goto(-16, -2)
    t.pendown()
    t.begin_fill()
    t.seth(-100)
    t.fd(40)
    t.left(50)
    t.fd(40)
    t.left(100)
    t.fd(40)
    t.left(55)
    t.fd(40)
    t.left(75)
    t.fd(30)
    t.end_fill()

    #裤子黑边
    t.color("black","black")
    t.penup()
    t.goto(-150, -45)
    t.pendown()
    t.seth(0)
    t.begin_fill()
    t.fd(45)
    baowei(-105,-45,20,45)
    t.end_fill()

    t.penup()
    t.goto(-75, -45)
    t.pendown()
    t.seth(0)
    t.begin_fill()
    t.fd(45)
    baowei(-30, -45, 20, 45)
    t.end_fill()

    t.penup()
    t.goto(30, -45)
    t.pendown()
    t.seth(0)
    t.begin_fill()
    t.fd(45)
    baowei(75, -45, 20, 45)
    t.end_fill()

    t.penup()
    t.goto(105, -45)
    t.pendown()
    t.seth(0)
    t.begin_fill()
    t.fd(45)
    baowei(150, -45, 20, 45)
    t.end_fill()

def jiao():
    #脚
    tx=-100
    ty=-100
    #画裤管
    t.color("black",(0.5,0.2,0.1))
    t.penup()
    t.goto(tx+50,ty+19)
    t.pendown()
    t.begin_fill()
    baowei(tx+50,ty+19,18,80)
    t.end_fill()
    #左腿
    t.penup()
    t.goto(tx+10,ty)
    t.pendown()
    t.color("black","yellow")
    t.begin_fill()
    baowei(tx+10,ty,110,10)
    t.end_fill()

    t.penup()
    t.goto(tx+10,ty-110)
    t.pendown()
    t.color("black","white")
    t.begin_fill()
    baowei(tx+10,ty-110,18,10)
    t.end_fill()

    t.penup()
    t.goto(tx + 10, ty - 128)
    t.pendown()
    t.color("black", "blue")
    t.begin_fill()
    baowei(tx + 10, ty - 128, 3, 10)
    t.end_fill()

    t.penup()
    t.goto(tx + 10, ty - 133)
    t.pendown()
    t.color("black", "white")
    t.begin_fill()
    baowei(tx + 10, ty - 133, 20, 10)
    t.end_fill()

    t.penup()
    t.goto(tx + 10, ty - 153)
    t.pendown()
    t.color("black", "red")
    t.begin_fill()
    baowei(tx + 10, ty - 153, 3, 10)
    t.end_fill()

    t.penup()
    t.goto(tx + 10, ty - 156)
    t.pendown()
    t.color("black", "white")
    t.begin_fill()
    baowei(tx + 10, ty - 156, 20, 10)
    t.end_fill()

    #左鞋
    t.goto(tx,ty-176)
    t.left(90)
    t.color("black","black")
    t.begin_fill()
    t.circle(15,45)
    t.right(70)
    t.circle(30,80)
    t.circle(10,130)
    t.seth(0)
    t.fd(65)
    t.left(60)
    t.circle(20,115)
    t.end_fill()

    #右腿
    tx=100
    ty=-100
    t.color("black",(0.5,0.2,0.1))
    t.penup()
    t.goto(tx+110,ty+19)
    t.pendown()
    t.begin_fill()
    baowei(tx+30,ty+19,18,80)
    t.end_fill()

    tx-=20
    t.penup()
    t.goto(tx + 10, ty)
    t.pendown()
    t.color("black", "yellow")
    t.begin_fill()
    baowei(tx + 10, ty, 110, 10)
    t.end_fill()

    t.penup()
    t.goto(tx + 10, ty - 110)
    t.pendown()
    t.color("black", "white")
    t.begin_fill()
    baowei(tx + 10, ty - 110, 18, 10)
    t.end_fill()

    t.penup()
    t.goto(tx + 10, ty - 128)
    t.pendown()
    t.color("black", "blue")
    t.begin_fill()
    baowei(tx + 10, ty - 128, 3, 10)
    t.end_fill()

    t.penup()
    t.goto(tx + 10, ty - 133)
    t.pendown()
    t.color("black", "white")
    t.begin_fill()
    baowei(tx + 10, ty - 133, 20, 10)
    t.end_fill()

    t.penup()
    t.goto(tx + 10, ty - 153)
    t.pendown()
    t.color("black", "red")
    t.begin_fill()
    baowei(tx + 10, ty - 153, 3, 10)
    t.end_fill()

    t.penup()
    t.goto(tx + 10, ty - 156)
    t.pendown()
    t.color("black", "white")
    t.begin_fill()
    baowei(tx + 10, ty - 156, 20, 10)
    t.end_fill()
    # 右鞋
    t.penup()
    t.goto(tx+10,ty-176)
    t.pendown()
    t.color("black","black")
    t.begin_fill()
    t.right(90)
    t.circle(-15, 45)
    t.left(70)
    t.circle(-30, 80)
    t.circle(-10, 130)
    t.seth(180)
    t.fd(65)
    t.right(60)
    t.circle(-20, 115)
    t.seth(180)
    t.end_fill()

def meimao(x,y,degree,dx,dy):
    t.seth(0)
    t.penup()
    t.goto(x + dx, y + dy)
    t.pendown()
    t.left(degree)
    t.fd(35)
    t.right(90)
    t.fd(6)
    t.right(90)
    t.fd(35)

def yanqiu(x,y):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.color("black","white")
    t.begin_fill()
    t.circle(60)
    t.end_fill()

    t.penup()
    t.goto(x+45, y)
    t.pendown()
    t.color("black", (0,0.5,0.7))
    t.begin_fill()
    t.circle(15)
    t.end_fill()

    t.penup()
    t.goto(x + 55, y)
    t.pendown()
    t.color("black", "black")
    t.begin_fill()
    t.circle(5)
    t.end_fill()

def lian():
    t.seth(0)
    t.right(90)
    tx = -130
    ty = 200

    #左
    yanqiu(tx,ty)

    t.color("black","black")
    t.penup()
    t.goto(tx+20,ty+42)
    t.pendown()
    t.begin_fill()
    meimao(tx,ty,130,20,42)
    t.end_fill()

    t.penup()
    t.goto(tx + 55, ty + 57)
    t.pendown()
    t.begin_fill()
    meimao(tx, ty, 90, 55, 57)
    t.end_fill()

    t.penup()
    t.goto(tx + 95, ty + 45)
    t.pendown()
    t.begin_fill()
    meimao(tx, ty, 50, 95, 45)
    t.end_fill()

    t.seth(0)
    t.right(90)
    tx = 15
    ty = 200
    #右
    yanqiu(tx,ty)
    
    t.color("black","black")
    t.penup()
    t.goto(tx+20,ty+42)
    t.pendown()
    t.begin_fill()
    meimao(tx,ty,130,20,42)
    t.end_fill()

    t.penup()
    t.goto(tx + 55, ty + 57)
    t.pendown()
    t.begin_fill()
    meimao(tx, ty, 90, 55, 57)
    t.end_fill()

    t.penup()
    t.goto(tx + 95, ty + 45)
    t.pendown()
    t.begin_fill()
    meimao(tx, ty, 50, 95, 45)
    t.end_fill()

    #鼻子
    t.penup()
    t.goto(0,110)
    t.pendown()
    t.seth(75)
    t.fd(40)
    t.circle(15,210)
    t.fd(40)

    #嘴
    t.penup()
    t.goto(-140,140)
    t.pendown()
    t.seth(-60)
    t.circle(120,55)
    t.circle(530,10)
    t.circle(120,55)

    #左嘴角
    tx=-125
    ty=145
    t.penup()
    t.goto(tx, ty)
    t.pendown()
    t.seth(70)
    t.circle(20,280)

    t.penup()
    t.goto(tx-10, ty)
    t.pendown()
    t.color("black","orange")
    t.begin_fill()
    t.circle(3)
    t.end_fill()

    t.penup()
    t.goto(tx-20, ty+8)
    t.pendown()
    t.begin_fill()
    t.circle(3)
    t.end_fill()

    t.penup()
    t.goto(tx-25, ty-2)
    t.pendown()
    t.begin_fill()
    t.circle(3)
    t.end_fill()

    #右嘴角
    tx=155
    ty=135

    t.penup()
    t.goto(tx, ty)
    t.pendown()
    t.seth(20)
    t.circle(20, 280)

    t.penup()
    t.goto(tx-15, ty+15)
    t.pendown()
    t.begin_fill()
    t.circle(3)
    t.end_fill()

    t.penup()
    t.goto(tx-5, ty+23)
    t.pendown()
    t.begin_fill()
    t.circle(3)
    t.end_fill()

    t.penup()
    t.goto(tx, ty+13)
    t.pendown()
    t.begin_fill()
    t.circle(3)
    t.end_fill()

    #牙
    t.penup()
    t.goto(-10, 76)
    t.pendown()
    t.color("black","white")
    t.begin_fill()
    baowei(-10,76,30,50)
    t.fd(5)
    t.end_fill()

    t.penup()
    t.goto(10, 76)
    t.pendown()
    t.seth(-90)
    t.begin_fill()
    t.fd(30)
    t.left(90)
    t.fd(50)
    t.left(90)
    t.fd(35)
    t.end_fill()

def shou():
    #右袖子
    t.seth(0)
    t.penup()
    t.goto(179,50)
    t.pendown()
    t.right(60)
    t.fd(50)
    t.left(90)
    t.circle(75,50)
    t.left(85)
    t.fd(57)

    #右手
    t.seth(180)
    t.penup()
    t.goto(365,97)
    t.pendown()
    t.color("black", "yellow")
    t.begin_fill()
    t.left(50)
    t.fd(130)
    t.right(90)
    t.fd(63)

    t.penup()
    t.goto(230, 28)
    t.pendown()
    t.seth(0)
    t.right(40)
    t.fd(68)
    t.left(90)
    t.fd(135)
    t.end_fill()

    #锅铲
    t.color("black", (0.5, 0.2, 0.1))
    t.begin_fill()
    baowei(410,140,120,32)
    t.goto(410,140)
    t.end_fill()

    t.penup()
    t.goto(380,140)
    t.pendown()
    t.color("black",(0.7,0.7,0.7))
    t.begin_fill()
    t.seth(0)
    t.fd(10)
    t.left(90)
    t.fd(60)

    t.left(30)
    t.fd(60)
    t.right(30)
    t.fd(40)
    t.right(90)
    t.fd(70)

    t.right(90)
    t.fd(40)
    t.right(30)
    t.fd(60)
    t.left(30)
    t.fd(60)
    t.left(90)
    t.fd(10)
    t.end_fill()

    t.color("black","white")
    t.penup()
    t.goto(377,280)
    t.pendown()
    t.begin_fill()
    t.seth(90)
    t.circle(5,180)
    t.fd(25)
    t.circle(5,180)
    t.fd(25)
    t.end_fill()

    t.penup()
    t.goto(401, 280)
    t.pendown()
    t.begin_fill()
    t.seth(90)
    t.circle(6, 180)
    t.fd(40)
    t.circle(6, 180)
    t.fd(40)
    t.end_fill()

    t.penup()
    t.goto(422, 280)
    t.pendown()
    t.seth(90)
    t.begin_fill()
    t.circle(5, 180)
    t.fd(25)
    t.circle(5, 180)
    t.fd(25)
    t.end_fill()

    #手掌
    t.color("black", "yellow")
    t.penup()
    t.goto(378,70)
    t.pendown()
    t.seth(0)
    t.begin_fill()
    t.left(140)
    t.circle(-43,80)
    t.circle(-5,120)
    t.circle(-80,20)
    t.end_fill()
    t.circle(-5,160)
    t.circle(-80, 15)

    #手指
    t.penup()
    t.goto(410,115)
    t.pendown()
    t.seth(0)
    t.right(75)
    t.fd(10)
    t.right(120)
    t.circle(55,30)
    t.begin_fill()
    t.circle(7,160)
    t.circle(80,20)
    t.circle(9,185)
    t.end_fill()

    t.penup()
    t.goto(380, 95)
    t.pendown()
    t.seth(0)
    t.right(150)
    t.begin_fill()
    t.circle(7, 143)
    t.circle(80, 25)
    t.circle(6, 185)
    t.end_fill()

    t.penup()
    t.goto(380, 85)
    t.pendown()
    t.begin_fill()
    t.seth(0)
    t.right(150)
    t.circle(7, 143)
    t.circle(80, 25)
    t.circle(6, 185)
    t.end_fill()

    #由于黑线条被填充颜色覆盖所以要再画一遍
    t.penup()
    t.goto(410, 115)
    t.pendown()
    t.seth(0)
    t.right(75)
    t.fd(10)
    t.right(120)
    t.circle(55, 30)
    t.circle(7, 160)
    t.circle(80, 20)
    t.circle(9, 185)

    t.penup()
    t.goto(380, 95)
    t.pendown()
    t.seth(0)
    t.right(150)
    t.circle(7, 143)
    t.circle(80, 25)
    t.circle(6, 185)

    #左袖子
    t.seth(180)
    t.penup()
    t.goto(-174, 0)
    t.pendown()
    t.circle(-40,60)
    t.right(48)
    t.fd(91)

    #左手
    t.penup()
    t.goto(-174, 0)
    t.pendown()
    t.color("black","yellow")
    t.begin_fill()
    baowei(-174,0,150,10)
    t.end_fill()

    t.penup()
    t.goto(-174,-150)
    t.pendown()
    t.seth(-90)
    t.begin_fill()
    t.circle(-240,10)
    t.circle(-4,160)
    t.circle(-160, 4)
    t.left(190)
    t.circle(-220,10)
    t.circle(-5,160)
    t.circle(-75, 60)
    t.end_fill()

    t.penup()
    t.goto(800,300)
    t.pendown()

shenti()
kuzi()
jiao()
lian()
shou()

t.done()